const graphData = {
  nodes: [
    { id: "theme_blackwell", type: "theme", title: "NVIDIA Blackwell Supply Chain", titleZh: "NVIDIA Blackwell产业链", status: "confirmed", layer: "theme", x: 540, y: 36, summary: "First validation workspace for the V2 graph kernel.", properties: { research_domain: "AI compute", scope: "supply_chain" } },

    { id: "module_compute", type: "module", title: "Compute", status: "confirmed", layer: "module", x: 170, y: 130, properties: { category: "compute" } },
    { id: "module_memory", type: "module", title: "Memory", status: "confirmed", layer: "module", x: 400, y: 130, properties: { category: "memory" } },
    { id: "module_packaging", type: "module", title: "Advanced Packaging", status: "confirmed", layer: "module", x: 630, y: 130, properties: { category: "packaging" } },
    { id: "module_networking", type: "module", title: "Networking", status: "confirmed", layer: "module", x: 850, y: 130, properties: { category: "networking" } },
    { id: "module_power", type: "module", title: "Power", status: "confirmed", layer: "module", x: 170, y: 430, properties: { category: "power" } },
    { id: "module_cooling", type: "module", title: "Cooling", status: "confirmed", layer: "module", x: 400, y: 430, properties: { category: "cooling" } },
    { id: "module_server_odm", type: "module", title: "Server / ODM", status: "confirmed", layer: "module", x: 630, y: 430, properties: { category: "server" } },
    { id: "module_cloud", type: "module", title: "Cloud Customers", status: "confirmed", layer: "module", x: 850, y: 430, properties: { category: "cloud" } },

    { id: "product_blackwell_gpu", type: "product", title: "Blackwell GPU", status: "confirmed", layer: "product", x: 410, y: 255, summary: "Core Blackwell accelerator product family.", properties: { category: "compute", importance: "high", aliases: ["Blackwell", "NVIDIA Blackwell", "B200", "GB200"] } },
    { id: "product_gb200_nvl72", type: "product", title: "GB200 NVL72", status: "confirmed", layer: "product", x: 555, y: 255, summary: "Blackwell-based rack-scale system.", properties: { category: "system" } },
    { id: "product_ai_server", type: "product", title: "AI Server", status: "confirmed", layer: "product", x: 675, y: 365, summary: "Server platform hosting AI accelerators.", properties: { category: "server" } },
    { id: "product_800g_optical_module", type: "product", title: "800G Optical Module", status: "confirmed", layer: "product", x: 920, y: 255, summary: "Optical interconnect product for AI data center networking.", properties: { category: "networking" } },
    { id: "product_1_6t_optical_module", type: "product", title: "1.6T Optical Module", status: "candidate", layer: "product", x: 920, y: 340, summary: "Next-generation optical module category.", properties: { category: "networking", watch_item: true } },
    { id: "product_ethernet_switch", type: "product", title: "Ethernet Switch", status: "confirmed", layer: "product", x: 820, y: 200, summary: "Switching product category for AI clusters.", properties: { category: "networking" } },
    { id: "product_infiniband_switch", type: "product", title: "InfiniBand Switch", status: "confirmed", layer: "product", x: 820, y: 310, summary: "Switching product category for AI clusters.", properties: { category: "networking" } },

    { id: "tech_hbm3e", type: "technology", title: "HBM3E", titleZh: "HBM3E高带宽内存", status: "confirmed", layer: "technology", x: 315, y: 250, summary: "Key high-bandwidth memory generation for AI accelerators.", properties: { category: "memory", importance: "high" } },
    { id: "tech_hbm4", type: "technology", title: "HBM4", status: "candidate", layer: "technology", x: 315, y: 335, summary: "Later-generation memory node; candidate watch item.", properties: { category: "memory", watch_item: true } },
    { id: "tech_cowos", type: "technology", title: "CoWoS", status: "confirmed", layer: "technology", x: 610, y: 250, summary: "Advanced packaging technology associated with AI accelerators.", properties: { category: "packaging", importance: "high" } },
    { id: "tech_advanced_substrate", type: "technology", title: "Advanced Substrate", status: "candidate", layer: "technology", x: 610, y: 335, summary: "Packaging substrate and interposer-related supply chain.", properties: { category: "packaging", watch_item: true } },
    { id: "tech_nvlink", type: "technology", title: "NVLink", status: "confirmed", layer: "technology", x: 735, y: 185, summary: "NVIDIA high-speed interconnect.", properties: { category: "networking" } },
    { id: "tech_infiniband", type: "technology", title: "InfiniBand", status: "confirmed", layer: "technology", x: 735, y: 275, summary: "AI cluster networking technology.", properties: { category: "networking" } },
    { id: "tech_ethernet_ai_fabric", type: "technology", title: "Ethernet AI Fabric", status: "candidate", layer: "technology", x: 735, y: 365, summary: "Ethernet-based AI networking architecture.", properties: { category: "networking" } },
    { id: "tech_liquid_cooling", type: "technology", title: "Liquid Cooling", status: "confirmed", layer: "technology", x: 395, y: 515, summary: "Cooling technology for high-density AI systems.", properties: { category: "cooling" } },
    { id: "tech_power_management", type: "technology", title: "Power Management", status: "confirmed", layer: "technology", x: 160, y: 515, summary: "Power conversion and management for AI data centers and servers.", properties: { category: "power" } },
    { id: "tech_data_center_power", type: "technology", title: "Data Center Power", status: "confirmed", layer: "technology", x: 160, y: 600, summary: "Facility and rack-level power infrastructure.", properties: { category: "power" } },

    { id: "company_nvidia", type: "company", title: "NVIDIA", status: "confirmed", layer: "company", x: 195, y: 250, properties: { ticker: "NVDA", market: "NASDAQ", category: "compute", market_snapshot: { return_1d: 1.8, fetch_quality: "placeholder" } } },
    { id: "company_tsmc", type: "company", title: "TSMC", status: "confirmed", layer: "company", x: 610, y: 365, properties: { ticker: "TSM", market: "NYSE", category: "foundry_packaging", market_snapshot: { return_1d: 0.7, fetch_quality: "placeholder" } } },
    { id: "company_sk_hynix", type: "company", title: "SK hynix", status: "confirmed", layer: "company", x: 185, y: 335, properties: { ticker: "000660.KS", market: "KRX", category: "memory" } },
    { id: "company_micron", type: "company", title: "Micron", status: "confirmed", layer: "company", x: 185, y: 410, properties: { ticker: "MU", market: "NASDAQ", category: "memory", market_snapshot: { return_1d: 2.1, fetch_quality: "placeholder" } } },
    { id: "company_samsung", type: "company", title: "Samsung Electronics", status: "confirmed", layer: "company", x: 315, y: 410, properties: { ticker: "005930.KS", market: "KRX", category: "memory", aliases: ["Samsung"] } },
    { id: "company_broadcom", type: "company", title: "Broadcom", status: "confirmed", layer: "company", x: 1040, y: 185, properties: { ticker: "AVGO", market: "NASDAQ", category: "networking" } },
    { id: "company_marvell", type: "company", title: "Marvell", status: "confirmed", layer: "company", x: 1040, y: 255, properties: { ticker: "MRVL", market: "NASDAQ", category: "networking" } },
    { id: "company_vertiv", type: "company", title: "Vertiv", status: "confirmed", layer: "company", x: 275, y: 600, properties: { ticker: "VRT", market: "NYSE", category: "power_cooling" } },
    { id: "company_supermicro", type: "company", title: "Supermicro", status: "confirmed", layer: "company", x: 675, y: 515, properties: { ticker: "SMCI", market: "NASDAQ", category: "server" } },
    { id: "company_foxconn_industrial_internet", type: "company", title: "Foxconn Industrial Internet", status: "confirmed", layer: "company", x: 675, y: 600, properties: { ticker: "601138.SS", market: "SSE", category: "server_odm" } },
    { id: "company_quanta", type: "company", title: "Quanta Computer", status: "confirmed", layer: "company", x: 805, y: 515, properties: { ticker: "2382.TW", market: "TWSE", category: "server_odm" } },
    { id: "company_wiwynn", type: "company", title: "Wiwynn", status: "confirmed", layer: "company", x: 805, y: 600, properties: { ticker: "6669.TW", market: "TWSE", category: "server_odm" } },
    { id: "company_coherent", type: "company", title: "Coherent", status: "confirmed", layer: "company", x: 1040, y: 340, properties: { ticker: "COHR", market: "NYSE", category: "optical" } },
    { id: "company_lumentum", type: "company", title: "Lumentum", status: "confirmed", layer: "company", x: 1040, y: 410, properties: { ticker: "LITE", market: "NASDAQ", category: "optical" } },
    { id: "company_innolight", type: "company", title: "Innolight", status: "confirmed", layer: "company", x: 920, y: 515, properties: { ticker: "300308.SZ", market: "SZSE", category: "optical" } },
    { id: "company_eoptolink", type: "company", title: "Eoptolink", status: "confirmed", layer: "company", x: 1040, y: 515, properties: { ticker: "300502.SZ", market: "SZSE", category: "optical" } },

    { id: "metric_hbm_asp", type: "metric", title: "HBM ASP", status: "confirmed", layer: "metric", x: 430, y: 345, summary: "Pricing signal for HBM supply-demand conditions.", properties: { category: "memory", metric_kind: "industry" } },
    { id: "metric_hbm_capacity", type: "metric", title: "HBM Capacity", status: "confirmed", layer: "metric", x: 430, y: 420, summary: "Supply capacity and ramp signal.", properties: { category: "memory", metric_kind: "industry" } },
    { id: "metric_cowos_capacity", type: "metric", title: "CoWoS Capacity", status: "confirmed", layer: "metric", x: 500, y: 365, summary: "Advanced packaging bottleneck signal.", properties: { category: "packaging", metric_kind: "industry" } },
    { id: "metric_cloud_capex", type: "metric", title: "Cloud CapEx", status: "confirmed", layer: "metric", x: 920, y: 600, summary: "Demand-side signal for AI infrastructure.", properties: { category: "cloud", metric_kind: "demand" } },
    { id: "metric_optical_module_shipments", type: "metric", title: "Optical Module Shipments", status: "confirmed", layer: "metric", x: 920, y: 430, summary: "Demand signal for AI networking.", properties: { category: "networking", metric_kind: "industry" } },
    { id: "metric_power_density", type: "metric", title: "Rack Power Density", status: "confirmed", layer: "metric", x: 275, y: 515, summary: "Power and cooling intensity signal.", properties: { category: "power_cooling", metric_kind: "industry" } }
  ],
  relations: [
    ["theme_blackwell", "contains", "module_compute", "confirmed", "high", "grouping"],
    ["theme_blackwell", "contains", "module_memory", "confirmed", "high", "grouping"],
    ["theme_blackwell", "contains", "module_packaging", "confirmed", "high", "grouping"],
    ["theme_blackwell", "contains", "module_networking", "confirmed", "high", "grouping"],
    ["theme_blackwell", "contains", "module_power", "confirmed", "high", "grouping"],
    ["theme_blackwell", "contains", "module_cooling", "confirmed", "high", "grouping"],
    ["theme_blackwell", "contains", "module_server_odm", "confirmed", "high", "grouping"],
    ["theme_blackwell", "contains", "module_cloud", "confirmed", "high", "grouping"],
    ["module_compute", "groups", "product_blackwell_gpu", "confirmed", "high", "grouping"],
    ["module_compute", "groups", "product_gb200_nvl72", "confirmed", "high", "grouping"],
    ["module_memory", "groups", "tech_hbm3e", "confirmed", "high", "grouping"],
    ["module_memory", "groups", "tech_hbm4", "candidate", "medium", "watch"],
    ["module_packaging", "groups", "tech_cowos", "confirmed", "high", "grouping"],
    ["module_packaging", "groups", "tech_advanced_substrate", "candidate", "medium", "watch"],
    ["module_networking", "groups", "tech_nvlink", "confirmed", "high", "grouping"],
    ["module_networking", "groups", "tech_infiniband", "confirmed", "high", "grouping"],
    ["module_networking", "groups", "tech_ethernet_ai_fabric", "candidate", "medium", "watch"],
    ["module_networking", "groups", "product_800g_optical_module", "confirmed", "high", "grouping"],
    ["module_networking", "groups", "product_1_6t_optical_module", "candidate", "medium", "watch"],
    ["module_power", "groups", "tech_power_management", "confirmed", "high", "grouping"],
    ["module_power", "groups", "tech_data_center_power", "confirmed", "high", "grouping"],
    ["module_cooling", "groups", "tech_liquid_cooling", "confirmed", "high", "grouping"],
    ["module_server_odm", "groups", "product_ai_server", "confirmed", "high", "grouping"],

    ["product_blackwell_gpu", "requires", "tech_hbm3e", "candidate", "high", "required"],
    ["product_blackwell_gpu", "requires", "tech_cowos", "candidate", "high", "required"],
    ["product_blackwell_gpu", "enables", "tech_nvlink", "candidate", "high", "required"],
    ["product_gb200_nvl72", "requires", "product_blackwell_gpu", "candidate", "high", "required"],
    ["product_gb200_nvl72", "requires", "tech_liquid_cooling", "candidate", "medium", "required"],
    ["product_ai_server", "requires", "tech_power_management", "candidate", "medium", "required"],
    ["product_ai_server", "requires", "tech_data_center_power", "candidate", "medium", "useful"],
    ["product_ai_server", "drives", "product_800g_optical_module", "candidate", "medium", "useful"],
    ["product_ai_server", "drives", "product_1_6t_optical_module", "candidate", "low", "useful"],
    ["tech_cowos", "constrains", "product_blackwell_gpu", "candidate", "medium", "required"],
    ["metric_cowos_capacity", "affects", "product_blackwell_gpu", "candidate", "medium", "useful"],
    ["metric_hbm_capacity", "affects", "tech_hbm3e", "candidate", "medium", "useful"],
    ["metric_cloud_capex", "drives", "product_ai_server", "candidate", "medium", "useful"],

    ["company_nvidia", "designs", "product_blackwell_gpu", "candidate", "high", "required"],
    ["company_tsmc", "manufactures", "product_blackwell_gpu", "candidate", "high", "required"],
    ["company_tsmc", "enables", "tech_cowos", "candidate", "high", "required"],
    ["company_sk_hynix", "supplies", "tech_hbm3e", "candidate", "high", "required"],
    ["company_micron", "exposed_to", "tech_hbm3e", "candidate", "medium", "required"],
    ["company_samsung", "exposed_to", "tech_hbm3e", "candidate", "medium", "required"],
    ["company_broadcom", "exposed_to", "tech_ethernet_ai_fabric", "candidate", "medium", "useful"],
    ["company_marvell", "exposed_to", "tech_ethernet_ai_fabric", "candidate", "medium", "useful"],
    ["company_vertiv", "exposed_to", "tech_data_center_power", "candidate", "medium", "useful"],
    ["company_vertiv", "exposed_to", "tech_liquid_cooling", "candidate", "medium", "useful"],
    ["company_supermicro", "exposed_to", "product_ai_server", "candidate", "medium", "useful"],
    ["company_foxconn_industrial_internet", "exposed_to", "product_ai_server", "candidate", "medium", "useful"],
    ["company_quanta", "exposed_to", "product_ai_server", "candidate", "medium", "useful"],
    ["company_wiwynn", "exposed_to", "product_ai_server", "candidate", "medium", "useful"],
    ["company_coherent", "exposed_to", "product_800g_optical_module", "candidate", "medium", "useful"],
    ["company_lumentum", "exposed_to", "product_800g_optical_module", "candidate", "medium", "useful"],
    ["company_innolight", "exposed_to", "product_800g_optical_module", "candidate", "medium", "useful"],
    ["company_eoptolink", "exposed_to", "product_800g_optical_module", "candidate", "medium", "useful"]
  ].map((item, index) => ({
    id: `rel_${index + 1}`,
    source: item[0],
    type: item[1],
    target: item[2],
    status: item[3],
    confidence: item[4],
    properties: { evidence_priority: item[5] }
  })),
  references: [
    { id: "ref_nvidia_architecture", title: "NVIDIA Blackwell Architecture Material", source_type: "url", status: "processed", metadata: { publisher: "NVIDIA", published_at: "2024" } },
    { id: "ref_micron_hbm", title: "Micron HBM Product and Earnings Commentary", source_type: "transcript", status: "processed", metadata: { publisher: "Micron", published_at: "2024" } },
    { id: "ref_tsmc_packaging", title: "TSMC Advanced Packaging Commentary", source_type: "filing", status: "processed", metadata: { publisher: "TSMC", published_at: "2024" } }
  ],
  evidenceLinks: [
    { id: "ev_hbm_context", reference_id: "ref_nvidia_architecture", target_type: "node", target_id: "tech_hbm3e", status: "confirmed", support_level: "contextualizes", summary: "HBM3E is tracked as a high-importance memory dependency for AI accelerators." },
    { id: "ev_micron_candidate", reference_id: "ref_micron_hbm", target_type: "relation", target_id: "company_micron:exposed_to:tech_hbm3e", status: "candidate", support_level: "supports", summary: "Candidate evidence for Micron exposure to HBM3E; needs human review before confirmation." },
    { id: "ev_tsmc_candidate", reference_id: "ref_tsmc_packaging", target_type: "relation", target_id: "company_tsmc:enables:tech_cowos", status: "candidate", support_level: "supports", summary: "Candidate evidence for TSMC advanced packaging exposure." }
  ]
};
